add common labels
wolfi-dev/.github pull request #4
Opened 2022-11-11 13:54 UTC by patflynn

Signed-off-by: Patrick Flynn <patrick@chainguard.dev>

2022-11-11 15:35 UTC, cpanato requested changes

2022-11-11 15:35 UTC, cpanato commented on labels.json
> +    "color": "#54c1f0"
drop the #

2022-11-11 15:35 UTC, cpanato commented on labels.json
> +    "description": "used by teams to indicate issues that we want to represent in a roadmap view provided for sales/product. ETAs on these issues will be set at the start of a planning cycle and be u
the description should be <= 100 chars

2022-11-11 21:19 UTC, patflynn commented
doh! Forgot to update before I copied the labels over to the other repos.
Thanks for catching this!


On Fri, Nov 11, 2022 at 10:36 AM Carlos Tadeu Panato Junior <
***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In labels.json
> <https://github.com/wolfi-dev/.github/pull/4#discussion_r1020327264>:
>
> > @@ -1,7 +1,82 @@
>  [
>    {
> -    "name": "test",
> -    "description": null,
> -    "color": "3e4b9e"
> +    "name": "needs-triage",
> +    "description": "applied to all new customer/user issues. Removed after triage occurs.",
> +    "color": "#54c1f0"
>
> drop the #
> ------------------------------
>
> In labels.json
> <https://github.com/wolfi-dev/.github/pull/4#discussion_r1020327474>:
>
> > +    "description": "production incident handled by on-call",
> +    "color": "#fa2302"
> +  },
> +  {
> +    "name": "post-mortem",
> +    "description": "post-mortem related issues and PRs",
> +    "color": "#c40866"
> +  },
> +  {
> +    "name": "request-version-update",
> +    "description": "request for a newer version of a package",
> +    "color": "#6ded73"
> +  },
> +  {
> +    "name": "roadmap",
> +    "description": "used by teams to indicate issues that we want to represent in a roadmap view provided for sales/product. ETAs on these issues will be set at the start of a planning cycle and be updated weekly.",
>
> the description should be <= 100 chars
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/wolfi-dev/.github/pull/4#pullrequestreview-1177505443>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AB37SHLKJE4X6VFU5GF6HLDWHZRWTANCNFSM6AAAAAAR5T3FNQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-11-12 08:14 UTC, cpanato approved these changes

2022-11-12 08:14 UTC, merged